<a href="https://colab.research.google.com/github/DoItSon/playdata/blob/main/numpy_%EB%AC%B8%EC%A0%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [14]:
import numpy as np

## 1. MAE 와 RMSE 함수 구현하기
- 다음과 같이 실제 값과 , 모델이 예측한 값이 각각 100개가 있다.
- 실제값과 예측값 사이에 평균 오차를 구하는 함수 두개를 구현해보자.

In [15]:
np.random.seed(42) 
target = np.random.randint(50, 91,100) # 정답값
pred = np.random.randint(40, 100,100) # 예측값
target , pred

(array([88, 78, 64, 57, 70, 88, 68, 72, 60, 60, 73, 85, 89, 73, 52, 71, 51,
        73, 79, 87, 51, 70, 82, 61, 71, 74, 76, 77, 65, 64, 52, 86, 56, 70,
        58, 88, 67, 53, 74, 63, 58, 75, 51, 69, 77, 56, 57, 84, 63, 66, 85,
        89, 53, 51, 55, 53, 78, 67, 75, 83, 59, 85, 63, 80, 64, 57, 63, 72,
        89, 70, 65, 67, 73, 75, 74, 90, 78, 64, 50, 74, 56, 58, 73, 50, 57,
        73, 60, 66, 57, 84, 84, 82, 54, 88, 90, 77, 56, 58, 57, 61]),
 array([73, 72, 87, 94, 62, 63, 76, 74, 83, 79, 61, 66, 74, 40, 74, 76, 86,
        53, 42, 40, 44, 65, 94, 53, 78, 66, 48, 54, 54, 65, 81, 99, 52, 90,
        71, 78, 88, 91, 71, 43, 69, 76, 62, 78, 84, 54, 82, 68, 75, 52, 71,
        46, 98, 90, 61, 67, 41, 81, 84, 96, 92, 45, 67, 67, 83, 83, 59, 69,
        50, 97, 94, 67, 64, 78, 72, 40, 96, 66, 96, 91, 52, 80, 42, 78, 45,
        47, 66, 48, 76, 72, 90, 81, 83, 63, 54, 98, 93, 71, 71, 63]))

### MAE(Mean Absolute Error)
- 실제 값과 예측 값의 차이를 절대값으로 변환해 평균화
$$
MAE = \frac{1}{n}{\sum_{i=1}^{n}|y_i-\hat{y}_i|}
$$

```
아래 셀의 코드 작성하여 함수구현
```

In [16]:
a = (np.abs(np.subtract(target,pred)))
sum(a)/100

17.8

In [17]:
def mae(target,pred):
    a = (np.abs(np.subtract(target,pred)))
    return sum(a)/100

In [18]:
mae(target,pred)

17.8

### RMSE(Root Mean Squared Error)
- 실제 값과 예측 값의 차이를 제곱한 뒤 평균화한 후에 루트

$$
RMSE = \sqrt{\frac{1}{n}{\sum_{i=1}^{n}(y_i-\hat{y}_i)^2}}
$$

```
아래 셀의 코드 작성하여 함수구현
```

In [19]:
np.sqrt(np.divide(np.sum((np.subtract(target,pred))**2),100))

21.829796151132516

In [20]:
def rmse(target,pred):
    return np.sqrt(np.divide(np.sum((np.subtract(target,pred))**2),100))

In [21]:
rmse(target,pred)

21.829796151132516

## 2.시그모이드 함수 구현하기
- S와 같은 형태로 미분 가능한 0~1 사이의 값을 반환한다.
- 이진 분류에 출력 함수로 사용된다.
$$
y = \frac{1}{1+e^{-x}}
$$

- x 변수에 있는 배열의 요소들을 시그모이드 함수에 넣어 0 ~ 1 사이 값들로 변경하시오.

In [22]:
np.random.seed(42)
x = np.random.randint(-10,10,10)
x

array([-4,  9,  4,  0, -3, -4,  8,  0,  0, -7])

In [23]:
1/(1 + np.exp(-x))

array([1.79862100e-02, 9.99876605e-01, 9.82013790e-01, 5.00000000e-01,
       4.74258732e-02, 1.79862100e-02, 9.99664650e-01, 5.00000000e-01,
       5.00000000e-01, 9.11051194e-04])

```
아래 셀의 코드 작성하여 함수구현
```

In [24]:
def sigmoid(x):
    return 1/(1 + np.exp(-x))

In [25]:
sigmoid(x)

array([1.79862100e-02, 9.99876605e-01, 9.82013790e-01, 5.00000000e-01,
       4.74258732e-02, 1.79862100e-02, 9.99664650e-01, 5.00000000e-01,
       5.00000000e-01, 9.11051194e-04])

## 3.다음의 3행 2열형태의 배열에서 두개 열 위치를 바꾸시오.

In [26]:
np.random.seed(42)
arr = np.random.randint(50,100,[3,2])
arr

array([[88, 78],
       [64, 92],
       [57, 70]])

```
아래 셀의 코드 작성
```

In [27]:
arr[:,::-1] # 다시보기

array([[78, 88],
       [92, 64],
       [70, 57]])

## 4.다음의 배열에서 각행의 평균을 구하시오.

In [28]:
np.random.seed(42) 
arr = np.random.randint(50, 101, (4, 3))
arr

array([[88, 78, 64],
       [92, 57, 70],
       [88, 68, 72],
       [60, 60, 73]])

```
아래 셀의 코드 작성
```

In [29]:
arr.mean(axis = 1)

array([76.66666667, 73.        , 76.        , 64.33333333])

## 데이터 설명
- 다음은 2021년 삼성주식 데이터이다
- 시계열 학습이 가능한 형태로 변환되어있다.
- 행마다 10일치의 시작가 ,상한가 , 하한가, 종가 에 대한 행렬이 들어가 있다.

In [30]:
samsung_stock_3d = np.load("samsung_stock_2021_3d.npy")
samsung_stock_3d.shape

(234, 10, 4)

- 한행을 보면 2차원 행렬 형태로 되어있다. 
    - 행은 일자 
    - 열은 시작가,상한가,하한가,종가 순

In [31]:
samsung_stock_3d[0] 

array([[81000, 84400, 80200, 83000],
       [81600, 83900, 81600, 83900],
       [83300, 84500, 82100, 82200],
       [82800, 84200, 82700, 82900],
       [83300, 90000, 83000, 88800],
       [90000, 96800, 89500, 91000],
       [90300, 91400, 87800, 90600],
       [89800, 91200, 89100, 89700],
       [88700, 90000, 88700, 89700],
       [89800, 91800, 88000, 88000]])

## 머신러닝 모델에서 학습이 가능하게 2차원 형태로 변경해보자..


## 5.각 행의 행렬을 벡터 형태로 변환하여 데이터셋을 2차원형태로 변경해보세요.
- 출력 데이터셋의 shape -> (234,40)

```
아래 셀의 코드 작성
```

In [32]:
arr = np.reshape(samsung_stock_3d,(234,40))
arr

array([[81000, 84400, 80200, ..., 91800, 88000, 88000],
       [81600, 83900, 81600, ..., 87300, 84100, 85000],
       [83300, 84500, 82100, ..., 88000, 83600, 87000],
       ...,
       [78300, 78600, 77100, ..., 78300, 77500, 78100],
       [77400, 78200, 77000, ..., 79400, 78800, 79400],
       [77400, 77600, 76800, ..., 80000, 79300, 79900]])

In [33]:
samsung_stock_3d.reshape(samsung_stock_3d.shape[0],-1) # -1은 자동계산

array([[81000, 84400, 80200, ..., 91800, 88000, 88000],
       [81600, 83900, 81600, ..., 87300, 84100, 85000],
       [83300, 84500, 82100, ..., 88000, 83600, 87000],
       ...,
       [78300, 78600, 77100, ..., 78300, 77500, 78100],
       [77400, 78200, 77000, ..., 79400, 78800, 79400],
       [77400, 77600, 76800, ..., 80000, 79300, 79900]])

## 6.각행의 시작가 ,상한가 , 하한가, 종가별로 평균을 구해 2차원 형태로 변경해보세요.

```
아래 셀의 코드 작성
```

In [34]:
a = samsung_stock_3d.mean(axis = 1)
a

array([[86060., 88820., 85270., 86980.],
       [86620., 89110., 85660., 87180.],
       [86910., 89520., 85860., 87490.],
       [87480., 89970., 86300., 87990.],
       [87950., 90410., 86680., 88510.],
       [88520., 90380., 87060., 88310.],
       [88220., 89690., 86740., 88150.],
       [88070., 89470., 86610., 87760.],
       [87750., 89120., 86260., 87350.],
       [87200., 88680., 85710., 86750.],
       [86670., 88000., 85110., 86150.],
       [86180., 87610., 84800., 85950.],
       [86140., 87450., 84810., 85690.],
       [85720., 87090., 84500., 85430.],
       [85320., 86610., 84060., 84870.],
       [84730., 86040., 83630., 84540.],
       [84410., 85470., 83300., 83900.],
       [83930., 85030., 82920., 83500.],
       [83530., 84520., 82520., 83100.],
       [83590., 84410., 82530., 83150.],
       [83590., 84510., 82750., 83440.],
       [83810., 84590., 82950., 83460.],
       [83720., 84310., 82790., 83230.],
       [83470., 84050., 82550., 83030.],
       [83500., 

## 7. 5번과 6번에서 생성한 특성(열)들을 합쳐서 x_train 변수에 넣어주세요.

```
아래 셀의 코드 작성
```

In [35]:
x_train = np.concatenate([arr,a],axis = 1)
x_train

array([[81000., 84400., 80200., ..., 88820., 85270., 86980.],
       [81600., 83900., 81600., ..., 89110., 85660., 87180.],
       [83300., 84500., 82100., ..., 89520., 85860., 87490.],
       ...,
       [78300., 78600., 77100., ..., 78010., 76840., 77490.],
       [77400., 78200., 77000., ..., 78090., 77010., 77690.],
       [77400., 77600., 76800., ..., 78270., 77240., 77860.]])

## 8. x_train변수의 특성(열)들에 최대값과 최소값들을 구하시오.

```
아래 셀의 코드 작성
```

In [36]:
np.max(x_train,axis = 0),np.min(x_train,axis = 0)

(array([90300., 96800., 89500., 91000., 90300., 96800., 89500., 91000.,
        90300., 96800., 89500., 91000., 90300., 96800., 89500., 91000.,
        90300., 96800., 89500., 91000., 90300., 96800., 89500., 91000.,
        90300., 91800., 89100., 90600., 89800., 91800., 89100., 89700.,
        89800., 91800., 88700., 89700., 89800., 91800., 88000., 89400.,
        88520., 90410., 87060., 88510.]),
 array([68700., 69600., 68300., 68800., 68700., 69600., 68300., 68800.,
        68700., 69600., 68300., 68800., 68700., 69600., 68300., 68800.,
        68700., 69600., 68300., 68800., 68700., 69600., 68300., 68800.,
        68700., 69600., 68300., 68800., 68700., 69600., 68300., 68800.,
        68700., 69600., 68300., 68800., 68700., 69600., 68300., 68800.,
        70040., 70550., 69510., 69920.]))

## 9.x_train변수의 특성(열)들에 분위수기준으로 5% 지점값들과 95% 지점값들을 구하시오

```
아래 셀의 코드 작성
```

In [37]:
odd_1 = np.quantile(x_train,0.05,axis=0)
odd_2 = np.quantile(x_train,0.95,axis=0)
odd_1,odd_2

(array([70300. , 70965. , 70000. , 70200. , 70300. , 70965. , 70000. ,
        70200. , 70300. , 70965. , 70000. , 70200. , 70300. , 70965. ,
        70000. , 70200. , 70300. , 70965. , 70000. , 70200. , 70300. ,
        70965. , 70000. , 70200. , 70300. , 70965. , 70000. , 70200. ,
        70300. , 70965. , 70000. , 70200. , 70300. , 70965. , 70000. ,
        70200. , 70300. , 70965. , 70000. , 70200. , 70666.5, 71169.5,
        70043. , 70430. ]),
 array([86340. , 87805. , 85205. , 86245. , 86340. , 87805. , 85205. ,
        86245. , 86340. , 87805. , 85205. , 86245. , 86340. , 87805. ,
        85205. , 86245. , 86340. , 87805. , 85205. , 86245. , 86340. ,
        87440. , 85205. , 85740. , 86135. , 86715. , 84905. , 85600. ,
        85905. , 86270. , 84410. , 85470. , 85735. , 86200. , 84135. ,
        85335. , 85310. , 86070. , 84100. , 85105. , 86088. , 87506. ,
        84803.5, 85781. ]))

## 10. 이상치를 제거해보기
- x_train변수의 특성(열)들에 분위수 기준 5% 지점의 미만값들을 5% 지점값으로 변경하고
- 95% 지점을 초과하는 값들을 95% 지점값으로 변경해보세요.

```
아래 셀의 코드 작성
```

In [38]:
np.clip(x_train,odd_1,odd_2)

array([[81000. , 84400. , 80200. , ..., 87506. , 84803.5, 85781. ],
       [81600. , 83900. , 81600. , ..., 87506. , 84803.5, 85781. ],
       [83300. , 84500. , 82100. , ..., 87506. , 84803.5, 85781. ],
       ...,
       [78300. , 78600. , 77100. , ..., 78010. , 76840. , 77490. ],
       [77400. , 78200. , 77000. , ..., 78090. , 77010. , 77690. ],
       [77400. , 77600. , 76800. , ..., 78270. , 77240. , 77860. ]])

## 11.x_train 데이터셋에서 20%의 데이터의 인덱스들을 리스트(배열 가능)에 담아 5번 랜덤하게 반환하는 제너레이터(리스트 형태로 반환 가능) 함수를 만들어주세요
- 단, 5번 랜덤하게 반환하는 과정에서 동일한 행의 인덱스가 나오면 안된다.
    - 한번 나온 행의 인덱스는 다시 나오면 안된다는 의미
    - 모든 행의 인덱스가 한번씩은 무조건 나와야한다.
- 234행 나누기 5를 할경우 나머지가 생기기 때문에 5번째 나오는 인덱스가 담긴 리스트 혹은 배열의 크기는 앞서 나온 크기와 차이가 나도 된다.  
- 제너레이터가 어려우신 분들은 그냥 인덱스들을 담고 있는 리스트(배열)들을 리스트에 담아서 return 하셔도 됩니다.

```
아래 셀의 코드 작성하여 함수 구현
```

In [39]:
def split_dataset(dataset):
    a = []
    for i in range(len(dataset)):
        a.append(i)
        np.random.shuffle(a)
    for i in a:
        return dataset[a,i]

In [60]:
def split_dataset(dataset): # 인덱스들 = 인덱스 번호만 출력!
    a = []                  # 인덱스 결과 생각하면서 풀기!
    b = []

    for i in range(len(np.array(dataset))):
        a.append(i)
    np.random.shuffle(a)

    for i in range(5):
        if i == 4:
            b.append(a[i+(i*45):50+(i*46)])
        else:
            b.append(a[i+(i*45):46+(i*46)])
    return b

In [42]:
def split_dataset(dataset):
    pass

- 다음 셀은 위에 함수 실행 결과를 검증하는 부분

In [61]:
index_list = split_dataset(x_train)
lst = [] # 중복 인덱스가 있는지 확인하기 위한 리스트
for idx in index_list:
    print(idx)  # 리스트 내용 확인
    lst.extend(idx) # 중복 인덱스가 있는지 확인하기 위해 리스트에 담기
len(set(lst)) # 중복 제거후 크기가 데이터셋 크기와 같다면 성공!! 즉 234개면 성공!!

[28, 186, 101, 225, 54, 40, 136, 87, 175, 107, 69, 80, 126, 201, 9, 33, 2, 90, 91, 30, 70, 193, 174, 73, 76, 149, 72, 156, 120, 191, 68, 224, 0, 11, 179, 190, 55, 63, 97, 148, 102, 106, 18, 77, 173, 93]
[84, 39, 215, 161, 220, 79, 88, 138, 164, 100, 4, 58, 43, 86, 52, 207, 104, 166, 99, 122, 178, 199, 51, 142, 71, 82, 204, 61, 78, 121, 95, 155, 62, 129, 185, 14, 75, 13, 15, 154, 64, 19, 44, 35, 56, 222]
[212, 12, 117, 125, 49, 25, 218, 133, 229, 181, 42, 203, 176, 195, 171, 214, 210, 124, 183, 65, 22, 85, 46, 31, 113, 188, 132, 187, 209, 57, 221, 131, 105, 24, 17, 189, 66, 192, 137, 94, 140, 182, 23, 205, 123, 223]
[5, 116, 45, 16, 48, 34, 3, 169, 60, 110, 27, 96, 29, 170, 153, 26, 7, 50, 108, 37, 157, 21, 118, 114, 172, 231, 144, 134, 135, 180, 198, 200, 20, 141, 32, 67, 194, 168, 162, 206, 228, 109, 230, 145, 92, 152]
[202, 213, 83, 227, 165, 163, 211, 74, 115, 197, 233, 119, 53, 151, 147, 130, 208, 146, 217, 8, 159, 36, 196, 139, 47, 226, 1, 112, 59, 111, 89, 143, 6, 98, 41, 158, 15

234

## 12.시계열 학습데이터 만들기
- 다음의 데이터는 2021년도 삼성 주식 데이터이다.
- 열부분은 시작가 ,상한가 , 하한가, 종가 순으로 되어있다.
- 행은 2021년도 거래 일자이다.

In [ ]:
samsung_stock = np.load("samsung_stock_2021.npy")
samsung_stock.shape

In [ ]:
samsung_stock[-5:] # 뒤에 5행만 확인해보자

### 시계열 학습데이터로 변환하는 함수를 만드시오.
- samsung_stock 변수의 데이터는 2차원 데이터이다.
- 학습데이터는 행별로 10일치의 행과 4열(시작가 ,상한가 , 하한가, 종가) 형태의 행렬을 담고 있는 3차원 형태의 데이터셋으로 변경하시오.
- 정답데이터는 미래의 5일치의 종가를 예측해야 한다는 가정하에 행별로 미래의 5일치의 종가가 담긴 2차원 형태의 데이터셋으로 변경하시오. 
- 1일씩 이동하면서 데이터셋을 구성하시오.

```
아래 셀의 코드 작성하여 함수 구현
```

In [ ]:
def transform_data(samsung_stock,seq_len=10,pred_len=5):
    pass

In [ ]:
samsung_stock = np.load("samsung_stock_2021.npy")
samsung_stock.shape

In [ ]:
samsung_stock_3d = np.load("samsung_stock_2021_3d.npy")
samsung_stock_3d.shape

In [ ]:
def transform_data(samsung_stock,seq_len=10,pred_len=5):
    a = []
    b = []

    for i in range(len(samsung_stock)+1-seq_len-pred_len): # 전체 길이에 대한 이해가 부족했다.
        a.append(samsung_stock[i:i+seq_len]) # for문 i를 안에 넣는 것을 생각못했다.
        b.append(samsung_stock[i+seq_len:i+seq_len+pred_len,3])
    return np.array(a),np.array(b)

In [ ]:
transform_data(samsung_stock)

- 다음 셀들은 위에 함수 실행 결과를 검증하는 부분

In [ ]:
x_train , y_train = transform_data(samsung_stock)
x_train.shape, y_train.shape # ((234, 10, 4), (234, 5))

In [ ]:
x_samsung_stock = np.load("samsung_stock_2021_3d.npy")
y_samsung_stock = np.load("y_train.npy")
np.all(x_samsung_stock == x_train) , np.all(y_samsung_stock == y_train) # 둘다 True 가 나와야 성공!!